version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_sgs
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.nestjs_sgs.rule=Host(`console.alfenas.mg.gov.br`)
      - traefik.http.routers.nestjs_sgs.tls.certresolver=le
      - traefik.http.routers.nestjs_sgs.entrypoints=websecure
      - traefik.http.routers.nestjs_sgs.tls=true
      - traefik.http.routers.nestjs_sgs.service=nestjs_sgs
      - traefik.http.services.nestjs_sgs.loadbalancer.server.port=3015  
    environment:
      DATABASE_URL: "mysql://root:AA88xk62@187.87.80.22:3306/db_sgs"
      JWT_SECRET: "433498939"

networks:
  traefik_public:
    driver: overlay
    attachable: true