version: '3.8'

services:
  app:
    image: sgs_app:latest
    networks:
      - traefik_public
    environment:
      DATABASE_URL: "mysql://root:AA88xk62@187.87.80.22:3306/db_sgs"
      JWT_SECRET: "433498939"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
         - node.role == manager
      resources:
        limits:
          cpus: "0.2"
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nestjs_sgs.rule=Host(`api.sgs.alfenas.mg.gov.br`)"
        - "traefik.http.routers.nestjs_sgs.tls.certresolver=le"
        - "traefik.http.routers.nestjs_sgs.entrypoints=websecure"
        - "traefik.http.routers.nestjs_sgs.tls=true"
        - "traefik.http.routers.nestjs_sgs.service=nestjs_sgs"
        - "traefik.http.services.nestjs_sgs.loadbalancer.server.port=3015"

networks:
  traefik_public:
    external: true